### PR TITLE
Implemented userNotes in the RescueDetails page

### PR DESCRIPTION
**Pull request by DeclanLacey**
Currently, every time the note field is changed, it immediately updates the UserNotes field in airtable. This is done by passing the current value from the textarea input into the updateRescueInAirtable function.

### CODE REVIEW

**Comment by DeclanLacey** [comment]
@travissanderson I'm curious to see if you think that the efficiency of this solution may be a problem or not. Currently it makes an API call to update the field on every change, the other solution would be to add a save button and have it only be updated when it is saved. If you are able to take a look when you are free next I would appreciate it!

**Comment by travissanderson** [comment]
I think a save button would be a good idea since you never know when airtable might enforce a request rate limit or worse start charging for it. And since people will be doing it from cellphones in sometimes remote places they won’t have a fast connection so spamming it would end up being a bad experience. On Oct 12, 2024, at 8:35 PM, Declan Lacey ***@***.***> wrote:﻿
@travissanderson I'm curious to see if you think that the efficiency of this solution may be a problem or not. Currently it makes an API call to update the field on every change, the other solution would be to add a save button and have it only be updated when it is saved. If you are able to take a look when you are free next I would appreciate it!

**Comment by DeclanLacey** [comment]
@travissanderson I definitely agree. I'll work on implementing the save button later today. Thanks!

**Comment by DeclanLacey** [comment]
Updated solution to only update the backend when the save note button is clicked, also made some small CSS changes. All of the checks have passed, merging now.

**Pull request merged**
